// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvaAGhnLZkOLfYYHu4FoBsOwCawIELDnc',
    appId: '1:350428183769:android:158454f0dc9fd2cccbd2c8',
    messagingSenderId: '350428183769',
    projectId: 'quizly-flutter',
    storageBucket: 'quizly-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdr8TEtdi7q94dBqivf-eD1AYd340D-Ko',
    appId: '1:350428183769:ios:ed13c7e237e36037cbd2c8',
    messagingSenderId: '350428183769',
    projectId: 'quizly-flutter',
    storageBucket: 'quizly-flutter.firebasestorage.app',
    iosBundleId: 'com.example.quizly',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgJOMz4UduKvXq9qUOXo0rML6Kk3M0btQ',
    appId: '1:350428183769:web:5628dbade5f92fd3cbd2c8',
    messagingSenderId: '350428183769',
    projectId: 'quizly-flutter',
    authDomain: 'quizly-flutter.firebaseapp.com',
    storageBucket: 'quizly-flutter.firebasestorage.app',
  );
}
